package org.tingoo.gaapi.bean;

// Generated 2011-1-14 9:02:39 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private String id;
	private String name;
	private String code;
	private String parent;
	private Integer type;
	private Integer orderindex;
	private String isorg;
	private String ishaschid;
	private Integer oaid;
	private String basetype;
	private String islooktel;
	private Set<MemberDetail> memberDetails = new HashSet<MemberDetail>(0);

	public Department() {
	}

	public Department(String id) {
		this.id = id;
	}

	public Department(String id, String name, String code, String parent,
			Integer type, Integer orderindex, String isorg, String ishaschid,
			Integer oaid, String basetype, String islooktel,
			Set<MemberDetail> memberDetails) {
		this.id = id;
		this.name = name;
		this.code = code;
		this.parent = parent;
		this.type = type;
		this.orderindex = orderindex;
		this.isorg = isorg;
		this.ishaschid = ishaschid;
		this.oaid = oaid;
		this.basetype = basetype;
		this.islooktel = islooktel;
		this.memberDetails = memberDetails;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getParent() {
		return this.parent;
	}

	public void setParent(String parent) {
		this.parent = parent;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getOrderindex() {
		return this.orderindex;
	}

	public void setOrderindex(Integer orderindex) {
		this.orderindex = orderindex;
	}

	public String getIsorg() {
		return this.isorg;
	}

	public void setIsorg(String isorg) {
		this.isorg = isorg;
	}

	public String getIshaschid() {
		return this.ishaschid;
	}

	public void setIshaschid(String ishaschid) {
		this.ishaschid = ishaschid;
	}

	public Integer getOaid() {
		return this.oaid;
	}

	public void setOaid(Integer oaid) {
		this.oaid = oaid;
	}

	public String getBasetype() {
		return this.basetype;
	}

	public void setBasetype(String basetype) {
		this.basetype = basetype;
	}

	public String getIslooktel() {
		return this.islooktel;
	}

	public void setIslooktel(String islooktel) {
		this.islooktel = islooktel;
	}

	public Set<MemberDetail> getMemberDetails() {
		return this.memberDetails;
	}

	public void setMemberDetails(Set<MemberDetail> memberDetails) {
		this.memberDetails = memberDetails;
	}

}
