package org.tingoo.gaapi.bean;

// Generated 2011-1-14 9:02:39 by Hibernate Tools 3.2.4.GA

import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Fault generated by hbm2java
 */
public class Fault implements java.io.Serializable {

	private int id;
	private MemberDetail memberDetailByPostman;
	private MemberDetail memberDetailByOpman;
	private Clob description;
	private Date createtime;
	private Date finishtime;
	private String posttel;
	private Set<Process> processes = new HashSet<Process>(0);

	public Fault() {
	}

	public Fault(int id) {
		this.id = id;
	}

	public Fault(int id, MemberDetail memberDetailByPostman,
			MemberDetail memberDetailByOpman, Clob description,
			Date createtime, Date finishtime, String posttel,
			Set<Process> processes) {
		this.id = id;
		this.memberDetailByPostman = memberDetailByPostman;
		this.memberDetailByOpman = memberDetailByOpman;
		this.description = description;
		this.createtime = createtime;
		this.finishtime = finishtime;
		this.posttel = posttel;
		this.processes = processes;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public MemberDetail getMemberDetailByPostman() {
		return this.memberDetailByPostman;
	}

	public void setMemberDetailByPostman(MemberDetail memberDetailByPostman) {
		this.memberDetailByPostman = memberDetailByPostman;
	}

	public MemberDetail getMemberDetailByOpman() {
		return this.memberDetailByOpman;
	}

	public void setMemberDetailByOpman(MemberDetail memberDetailByOpman) {
		this.memberDetailByOpman = memberDetailByOpman;
	}

	public Clob getDescription() {
		return this.description;
	}

	public void setDescription(Clob description) {
		this.description = description;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getFinishtime() {
		return this.finishtime;
	}

	public void setFinishtime(Date finishtime) {
		this.finishtime = finishtime;
	}

	public String getPosttel() {
		return this.posttel;
	}

	public void setPosttel(String posttel) {
		this.posttel = posttel;
	}

	public Set<Process> getProcesses() {
		return this.processes;
	}

	public void setProcesses(Set<Process> processes) {
		this.processes = processes;
	}

}
