package org.tingoo.gaapi.bean;

// Generated 2010-12-23 15:14:14 by Hibernate Tools 3.2.4.GA

import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Fault generated by hbm2java
 */
public class Fault implements java.io.Serializable {

	private int id;
	private Member memberByPostman;
	private Member memberByOpman;
	private Clob description;
	private Date createtime;
	private Date finishtime;
	private String posttel;
	private Set<Process> processes = new HashSet<Process>(0);

	public Fault() {
	}

	public Fault(int id) {
		this.id = id;
	}

	public Fault(int id, Member memberByPostman, Member memberByOpman,
			Clob description, Date createtime, Date finishtime, String posttel,
			Set<Process> processes) {
		this.id = id;
		this.memberByPostman = memberByPostman;
		this.memberByOpman = memberByOpman;
		this.description = description;
		this.createtime = createtime;
		this.finishtime = finishtime;
		this.posttel = posttel;
		this.processes = processes;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Member getMemberByPostman() {
		return this.memberByPostman;
	}

	public void setMemberByPostman(Member memberByPostman) {
		this.memberByPostman = memberByPostman;
	}

	public Member getMemberByOpman() {
		return this.memberByOpman;
	}

	public void setMemberByOpman(Member memberByOpman) {
		this.memberByOpman = memberByOpman;
	}

	public Clob getDescription() {
		return this.description;
	}

	public void setDescription(Clob description) {
		this.description = description;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getFinishtime() {
		return this.finishtime;
	}

	public void setFinishtime(Date finishtime) {
		this.finishtime = finishtime;
	}

	public String getPosttel() {
		return this.posttel;
	}

	public void setPosttel(String posttel) {
		this.posttel = posttel;
	}

	public Set<Process> getProcesses() {
		return this.processes;
	}

	public void setProcesses(Set<Process> processes) {
		this.processes = processes;
	}

}
