package org.tingoo.gaapi.bean;

// Generated 2010-12-23 15:14:14 by Hibernate Tools 3.2.4.GA

/**
 * GroupContact generated by hbm2java
 */
public class GroupContact implements java.io.Serializable {

	private int id;
	private Member member;
	private Group group;
	private String name;
	private String mobile;

	public GroupContact() {
	}

	public GroupContact(int id) {
		this.id = id;
	}

	public GroupContact(int id, Member member, Group group, String name,
			String mobile) {
		this.id = id;
		this.member = member;
		this.group = group;
		this.name = name;
		this.mobile = mobile;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

}
