package org.tingoo.gaapi.bean;

// Generated 2010-12-23 15:14:14 by Hibernate Tools 3.2.4.GA

import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group implements java.io.Serializable {

	private int id;
	private Member member;
	private String name;
	private Clob description;
	private Date createtime;
	private String share;
	private Set<GroupContact> groupContacts = new HashSet<GroupContact>(0);

	public Group() {
	}

	public Group(int id) {
		this.id = id;
	}

	public Group(int id, Member member, String name, Clob description,
			Date createtime, String share, Set<GroupContact> groupContacts) {
		this.id = id;
		this.member = member;
		this.name = name;
		this.description = description;
		this.createtime = createtime;
		this.share = share;
		this.groupContacts = groupContacts;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Clob getDescription() {
		return this.description;
	}

	public void setDescription(Clob description) {
		this.description = description;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public String getShare() {
		return this.share;
	}

	public void setShare(String share) {
		this.share = share;
	}

	public Set<GroupContact> getGroupContacts() {
		return this.groupContacts;
	}

	public void setGroupContacts(Set<GroupContact> groupContacts) {
		this.groupContacts = groupContacts;
	}

}
