package org.tingoo.gaapi.bean;

// Generated 2011-1-10 11:05:16 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Member generated by hbm2java
 */
public class Member implements java.io.Serializable {

	private String id;
	private Department department;
	private String username;
	private String password;
	private String isapproved;
	private String islockedout;
	private String createdate;
	private Integer orderindex;
	private String policeid;
	private String membername;
	private String sex;
	private String duty;
	private String birthday;
	private String ismarry;
	private String shortmobile;
	private String mobile;
	private String officephone;
	private String type;
	private String state;
	private String startworkdate;
	private String createtime;
	private String modifytime;
	private String innerofficephone;
	private Set<Group> groups = new HashSet<Group>(0);
	private Set<Fault> faultsForPostman = new HashSet<Fault>(0);
	private Set<Process> processes = new HashSet<Process>(0);
	private Set<User> users = new HashSet<User>(0);
	private Set<GroupContact> groupContacts = new HashSet<GroupContact>(0);
	private Set<Fault> faultsForOpman = new HashSet<Fault>(0);

	public Member() {
	}

	public Member(String id) {
		this.id = id;
	}

	public Member(String id, Department department, String username,
			String password, String isapproved, String islockedout,
			String createdate, Integer orderindex, String policeid,
			String membername, String sex, String duty, String birthday,
			String ismarry, String shortmobile, String mobile,
			String officephone, String type, String state,
			String startworkdate, String createtime, String modifytime,
			String innerofficephone, Set<Group> groups,
			Set<Fault> faultsForPostman, Set<Process> processes,
			Set<User> users, Set<GroupContact> groupContacts,
			Set<Fault> faultsForOpman) {
		this.id = id;
		this.department = department;
		this.username = username;
		this.password = password;
		this.isapproved = isapproved;
		this.islockedout = islockedout;
		this.createdate = createdate;
		this.orderindex = orderindex;
		this.policeid = policeid;
		this.membername = membername;
		this.sex = sex;
		this.duty = duty;
		this.birthday = birthday;
		this.ismarry = ismarry;
		this.shortmobile = shortmobile;
		this.mobile = mobile;
		this.officephone = officephone;
		this.type = type;
		this.state = state;
		this.startworkdate = startworkdate;
		this.createtime = createtime;
		this.modifytime = modifytime;
		this.innerofficephone = innerofficephone;
		this.groups = groups;
		this.faultsForPostman = faultsForPostman;
		this.processes = processes;
		this.users = users;
		this.groupContacts = groupContacts;
		this.faultsForOpman = faultsForOpman;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getIsapproved() {
		return this.isapproved;
	}

	public void setIsapproved(String isapproved) {
		this.isapproved = isapproved;
	}

	public String getIslockedout() {
		return this.islockedout;
	}

	public void setIslockedout(String islockedout) {
		this.islockedout = islockedout;
	}

	public String getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(String createdate) {
		this.createdate = createdate;
	}

	public Integer getOrderindex() {
		return this.orderindex;
	}

	public void setOrderindex(Integer orderindex) {
		this.orderindex = orderindex;
	}

	public String getPoliceid() {
		return this.policeid;
	}

	public void setPoliceid(String policeid) {
		this.policeid = policeid;
	}

	public String getMembername() {
		return this.membername;
	}

	public void setMembername(String membername) {
		this.membername = membername;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getDuty() {
		return this.duty;
	}

	public void setDuty(String duty) {
		this.duty = duty;
	}

	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public String getIsmarry() {
		return this.ismarry;
	}

	public void setIsmarry(String ismarry) {
		this.ismarry = ismarry;
	}

	public String getShortmobile() {
		return this.shortmobile;
	}

	public void setShortmobile(String shortmobile) {
		this.shortmobile = shortmobile;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getOfficephone() {
		return this.officephone;
	}

	public void setOfficephone(String officephone) {
		this.officephone = officephone;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getStartworkdate() {
		return this.startworkdate;
	}

	public void setStartworkdate(String startworkdate) {
		this.startworkdate = startworkdate;
	}

	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	public String getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(String modifytime) {
		this.modifytime = modifytime;
	}

	public String getInnerofficephone() {
		return this.innerofficephone;
	}

	public void setInnerofficephone(String innerofficephone) {
		this.innerofficephone = innerofficephone;
	}

	public Set<Group> getGroups() {
		return this.groups;
	}

	public void setGroups(Set<Group> groups) {
		this.groups = groups;
	}

	public Set<Fault> getFaultsForPostman() {
		return this.faultsForPostman;
	}

	public void setFaultsForPostman(Set<Fault> faultsForPostman) {
		this.faultsForPostman = faultsForPostman;
	}

	public Set<Process> getProcesses() {
		return this.processes;
	}

	public void setProcesses(Set<Process> processes) {
		this.processes = processes;
	}

	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	public Set<GroupContact> getGroupContacts() {
		return this.groupContacts;
	}

	public void setGroupContacts(Set<GroupContact> groupContacts) {
		this.groupContacts = groupContacts;
	}

	public Set<Fault> getFaultsForOpman() {
		return this.faultsForOpman;
	}

	public void setFaultsForOpman(Set<Fault> faultsForOpman) {
		this.faultsForOpman = faultsForOpman;
	}

}
