package org.tingoo.gaapi.bean;

// Generated 2011-1-14 9:02:39 by Hibernate Tools 3.2.4.GA

import java.sql.Clob;
import java.util.Date;

/**
 * Process generated by hbm2java
 */
public class Process implements java.io.Serializable {

	private int id;
	private Fault fault;
	private MemberDetail memberDetail;
	private String optype;
	private Clob result;
	private Date optime;

	public Process() {
	}

	public Process(int id) {
		this.id = id;
	}

	public Process(int id, Fault fault, MemberDetail memberDetail,
			String optype, Clob result, Date optime) {
		this.id = id;
		this.fault = fault;
		this.memberDetail = memberDetail;
		this.optype = optype;
		this.result = result;
		this.optime = optime;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Fault getFault() {
		return this.fault;
	}

	public void setFault(Fault fault) {
		this.fault = fault;
	}

	public MemberDetail getMemberDetail() {
		return this.memberDetail;
	}

	public void setMemberDetail(MemberDetail memberDetail) {
		this.memberDetail = memberDetail;
	}

	public String getOptype() {
		return this.optype;
	}

	public void setOptype(String optype) {
		this.optype = optype;
	}

	public Clob getResult() {
		return this.result;
	}

	public void setResult(Clob result) {
		this.result = result;
	}

	public Date getOptime() {
		return this.optime;
	}

	public void setOptime(Date optime) {
		this.optime = optime;
	}

}
