package org.tingoo.gaapi.bean;

// Generated 2011-1-14 9:02:39 by Hibernate Tools 3.2.4.GA

import java.sql.Clob;
import java.util.Date;

/**
 * Smslog generated by hbm2java
 */
public class Smslog implements java.io.Serializable {

	private int id;
	private Date sendtime;
	private Clob message;
	private Clob mobile;
	private String ip;

	public Smslog() {
	}

	public Smslog(int id) {
		this.id = id;
	}

	public Smslog(int id, Date sendtime, Clob message, Clob mobile, String ip) {
		this.id = id;
		this.sendtime = sendtime;
		this.message = message;
		this.mobile = mobile;
		this.ip = ip;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getSendtime() {
		return this.sendtime;
	}

	public void setSendtime(Date sendtime) {
		this.sendtime = sendtime;
	}

	public Clob getMessage() {
		return this.message;
	}

	public void setMessage(Clob message) {
		this.message = message;
	}

	public Clob getMobile() {
		return this.mobile;
	}

	public void setMobile(Clob mobile) {
		this.mobile = mobile;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

}
