package org.tingoo.gaapi.bean;

// Generated 2010-12-23 15:14:14 by Hibernate Tools 3.2.4.GA

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int id;
	private Member member;

	public User() {
	}

	public User(int id) {
		this.id = id;
	}

	public User(int id, Member member) {
		this.id = id;
		this.member = member;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

}
