package org.tingoo.gaapi.bean;

// Generated 2011-1-20 15:28:22 by Hibernate Tools 3.2.4.GA

/**
 * Wage generated by hbm2java
 */
public class Wage implements java.io.Serializable {

	private int id;
	private String code;
	private String name;
	private String deptcode;
	private String deptname;
	private String zhiwuGz;
	private String jibieGz;
	private String jishudengjiGz;
	private String gangweiGz;
	private String shenghuoBt;
	private String gongzuoJt1;
	private String gongzuoJt2;
	private String jingxianJt;
	private String teshuJt;
	private String zhufangBt;
	private String yiliao;
	private String tongxun;
	private String chegai;
	private String qita1;
	private String qita2;
	private String bufa;
	private String yingfa;
	private String gongjijing;
	private String geshui;
	private String yanglaobaoxian;
	private String yiliaobaoxian;
	private String shiyebaoxian;
	private String qitadaikou;
	private String koukuanheji;
	private String shifaheji;
	private String yuefen;
	private String beizhu;

	public Wage() {
	}

	public Wage(int id) {
		this.id = id;
	}

	public Wage(int id, String code, String name, String deptcode,
			String deptname, String zhiwuGz, String jibieGz,
			String jishudengjiGz, String gangweiGz, String shenghuoBt,
			String gongzuoJt1, String gongzuoJt2, String jingxianJt,
			String teshuJt, String zhufangBt, String yiliao, String tongxun,
			String chegai, String qita1, String qita2, String bufa,
			String yingfa, String gongjijing, String geshui,
			String yanglaobaoxian, String yiliaobaoxian, String shiyebaoxian,
			String qitadaikou, String koukuanheji, String shifaheji,
			String yuefen, String beizhu) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.deptcode = deptcode;
		this.deptname = deptname;
		this.zhiwuGz = zhiwuGz;
		this.jibieGz = jibieGz;
		this.jishudengjiGz = jishudengjiGz;
		this.gangweiGz = gangweiGz;
		this.shenghuoBt = shenghuoBt;
		this.gongzuoJt1 = gongzuoJt1;
		this.gongzuoJt2 = gongzuoJt2;
		this.jingxianJt = jingxianJt;
		this.teshuJt = teshuJt;
		this.zhufangBt = zhufangBt;
		this.yiliao = yiliao;
		this.tongxun = tongxun;
		this.chegai = chegai;
		this.qita1 = qita1;
		this.qita2 = qita2;
		this.bufa = bufa;
		this.yingfa = yingfa;
		this.gongjijing = gongjijing;
		this.geshui = geshui;
		this.yanglaobaoxian = yanglaobaoxian;
		this.yiliaobaoxian = yiliaobaoxian;
		this.shiyebaoxian = shiyebaoxian;
		this.qitadaikou = qitadaikou;
		this.koukuanheji = koukuanheji;
		this.shifaheji = shifaheji;
		this.yuefen = yuefen;
		this.beizhu = beizhu;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDeptcode() {
		return this.deptcode;
	}

	public void setDeptcode(String deptcode) {
		this.deptcode = deptcode;
	}

	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	public String getZhiwuGz() {
		return this.zhiwuGz;
	}

	public void setZhiwuGz(String zhiwuGz) {
		this.zhiwuGz = zhiwuGz;
	}

	public String getJibieGz() {
		return this.jibieGz;
	}

	public void setJibieGz(String jibieGz) {
		this.jibieGz = jibieGz;
	}

	public String getJishudengjiGz() {
		return this.jishudengjiGz;
	}

	public void setJishudengjiGz(String jishudengjiGz) {
		this.jishudengjiGz = jishudengjiGz;
	}

	public String getGangweiGz() {
		return this.gangweiGz;
	}

	public void setGangweiGz(String gangweiGz) {
		this.gangweiGz = gangweiGz;
	}

	public String getShenghuoBt() {
		return this.shenghuoBt;
	}

	public void setShenghuoBt(String shenghuoBt) {
		this.shenghuoBt = shenghuoBt;
	}

	public String getGongzuoJt1() {
		return this.gongzuoJt1;
	}

	public void setGongzuoJt1(String gongzuoJt1) {
		this.gongzuoJt1 = gongzuoJt1;
	}

	public String getGongzuoJt2() {
		return this.gongzuoJt2;
	}

	public void setGongzuoJt2(String gongzuoJt2) {
		this.gongzuoJt2 = gongzuoJt2;
	}

	public String getJingxianJt() {
		return this.jingxianJt;
	}

	public void setJingxianJt(String jingxianJt) {
		this.jingxianJt = jingxianJt;
	}

	public String getTeshuJt() {
		return this.teshuJt;
	}

	public void setTeshuJt(String teshuJt) {
		this.teshuJt = teshuJt;
	}

	public String getZhufangBt() {
		return this.zhufangBt;
	}

	public void setZhufangBt(String zhufangBt) {
		this.zhufangBt = zhufangBt;
	}

	public String getYiliao() {
		return this.yiliao;
	}

	public void setYiliao(String yiliao) {
		this.yiliao = yiliao;
	}

	public String getTongxun() {
		return this.tongxun;
	}

	public void setTongxun(String tongxun) {
		this.tongxun = tongxun;
	}

	public String getChegai() {
		return this.chegai;
	}

	public void setChegai(String chegai) {
		this.chegai = chegai;
	}

	public String getQita1() {
		return this.qita1;
	}

	public void setQita1(String qita1) {
		this.qita1 = qita1;
	}

	public String getQita2() {
		return this.qita2;
	}

	public void setQita2(String qita2) {
		this.qita2 = qita2;
	}

	public String getBufa() {
		return this.bufa;
	}

	public void setBufa(String bufa) {
		this.bufa = bufa;
	}

	public String getYingfa() {
		return this.yingfa;
	}

	public void setYingfa(String yingfa) {
		this.yingfa = yingfa;
	}

	public String getGongjijing() {
		return this.gongjijing;
	}

	public void setGongjijing(String gongjijing) {
		this.gongjijing = gongjijing;
	}

	public String getGeshui() {
		return this.geshui;
	}

	public void setGeshui(String geshui) {
		this.geshui = geshui;
	}

	public String getYanglaobaoxian() {
		return this.yanglaobaoxian;
	}

	public void setYanglaobaoxian(String yanglaobaoxian) {
		this.yanglaobaoxian = yanglaobaoxian;
	}

	public String getYiliaobaoxian() {
		return this.yiliaobaoxian;
	}

	public void setYiliaobaoxian(String yiliaobaoxian) {
		this.yiliaobaoxian = yiliaobaoxian;
	}

	public String getShiyebaoxian() {
		return this.shiyebaoxian;
	}

	public void setShiyebaoxian(String shiyebaoxian) {
		this.shiyebaoxian = shiyebaoxian;
	}

	public String getQitadaikou() {
		return this.qitadaikou;
	}

	public void setQitadaikou(String qitadaikou) {
		this.qitadaikou = qitadaikou;
	}

	public String getKoukuanheji() {
		return this.koukuanheji;
	}

	public void setKoukuanheji(String koukuanheji) {
		this.koukuanheji = koukuanheji;
	}

	public String getShifaheji() {
		return this.shifaheji;
	}

	public void setShifaheji(String shifaheji) {
		this.shifaheji = shifaheji;
	}

	public String getYuefen() {
		return this.yuefen;
	}

	public void setYuefen(String yuefen) {
		this.yuefen = yuefen;
	}

	public String getBeizhu() {
		return this.beizhu;
	}

	public void setBeizhu(String beizhu) {
		this.beizhu = beizhu;
	}

}
