document.writeln('<li><a href="../soft/4934.html" target="_blank"><img src="../images/4934.gif">腾讯QQ</a></li>');
document.writeln('<li><a href="../soft/28200.html" target="_blank"><img src="../images/28200.gif">飞信Fetion</a></li>');
document.writeln('<li><a href="../soft/16443.html" target="_blank"><img src="../images/16443.gif">Live Messenger(MSN)</a></li>');
document.writeln('<li><a href="../soft/21255.html" target="_blank"><img src="../images/21255.gif">阿里旺旺</a></li>');
document.writeln('<li><a href="../soft/15036.html" target="_blank"><img src="../images/15036.gif">腾讯TM</a></li>');
document.writeln('<li><a href="../soft/14920.html" target="_blank"><img src="../images/14920.gif">TOM-Skype</a></li>');
document.writeln('<li><a href="../soft/11669.html" target="_blank"><img src="../images/11669.gif">都秀视频聊天</a></li>');
document.writeln('<li><a href="../soft/21697.html" target="_blank"><img src="../images/21697.gif">TeamSpeak(TS)</a></li>');
document.writeln('<li><a href="../soft/41189.html" target="_blank"><img src="../images/41189.gif">彩虹2009</a></li>');
document.writeln('<li><a href="../soft/42412.html" target="_blank"><img src="../images/42412.gif">新浪UT Game</a></li>');
document.writeln('<li><a href="../soft/38027.html" target="_blank"><img src="../images/38027.gif">新浪UC</a></li>');
document.writeln('<li><a href="../soft/7654.html" target="_blank"><img src="../images/7654.gif">雅虎通</a></li>');
document.writeln('<li><a href="../soft/5284.html" target="_blank"><img src="../images/5284.gif">MSNShell</a></li>');
document.writeln('<li><a href="../soft/24551.html" target="_blank"><img src="../images/29688.gif">UUCall网络电话</a></li>');
document.writeln('<li><a href="../soft/51550.html" target="_blank"><img src="../images/51550.gif">呱呱视频聊天</a></li>');
document.writeln('<li><a href="../soft/20654.html" target="_blank"><img src="../images/20654.gif">阿里通网络电话</a></li>');
document.writeln('<li><a href="../soft/37741.html" target="_blank"><img src="../images/37741.gif">9158虚拟视频</a></li>');
document.writeln('<li><a href="../soft/26868.html" target="_blank"><img src="../images/26868.gif">KC网络电话</a></li>');
document.writeln('<li><a href="../soft/42758.html" target="_blank"><img src="../images/42758.gif">百度Hi</a></li>');