document.writeln('<li><a href="../soft/98.html" target="_blank"><img src="../images/98.gif">暴风影音</a></li>');
document.writeln('<li><a href="../soft/23111.html" target="_blank"><img src="../images/23111.gif">PPS网络电视</a></li>');
document.writeln('<li><a href="../soft/11350.html" target="_blank"><img src="../images/11350.gif">千千静听</a></li>');
document.writeln('<li><a href="../soft/14786.html" target="_blank"><img src="../images/14786.gif">酷狗音乐</a></li>');
document.writeln('<li><a href="../soft/1760.html" target="_blank"><img src="../images/1760.gif">RealPlayer</a></li>');
document.writeln('<li><a href="../soft/4641.html" target="_blank"><img src="../images/4641.gif">Winamp</a></li>');
document.writeln('<li><a href="../soft/31325.html" target="_blank"><img src="../images/31325.gif">酷我音乐盒</a></li>');
document.writeln('<li><a href="../soft/25709.html" target="_blank"><img src="../images/25709.gif">风行网络电影</a></li>');
document.writeln('<li><a href="../soft/24534.html" target="_blank"><img src="../images/24534.gif">快乐影音</a></li>');
document.writeln('<li><a href="../soft/24106.html" target="_blank"><img src="../images/24106.gif">PPLive</a></li>');
document.writeln('<li><a href="../soft/23968.html" target="_blank"><img src="../images/23968.gif">QQ直播(QQLive)</a></li>');
document.writeln('<li><a href="../soft/27438.html" target="_blank"><img src="../images/27438.gif">UUSee网络电视</a></li>');
document.writeln('<li><a href="../soft/6856.html" target="_blank"><img src="../images/6856.gif">Windows Media Player 9</a></li>');
document.writeln('<li><a href="../soft/20492.html" target="_blank"><img src="../images/20492.gif">Windows Media Player 10</a></li>');
document.writeln('<li><a href="../soft/17373.html" target="_blank"><img src="../images/17373.gif">Windows Media Player 11</a></li>');
document.writeln('<li><a href="../soft/17654.html" target="_blank"><img src="../images/17654.gif">超级转换秀</a></li>');
document.writeln('<li><a href="../soft/23609.html" target="_blank"><img src="../images/23609.gif">KMPlayer</a></li>');
document.writeln('<li><a href="../soft/35396.html" target="_blank"><img src="../images/35396.gif">沸点网络电视</a></li>');
document.writeln('<li><a href="../soft/1672.html" target="_blank"><img src="../images/1672.gif">Nero Burning ROM</a></li>');
document.writeln('<li><a href="../soft/10360.html" target="_blank"><img src="../images/10360.gif">Foobar2000</a></li>');
document.writeln('<li><a href="../soft/31421.html" target="_blank"><img src="../images/31421.gif">一听音乐盒</a></li>');
document.writeln('<li><a href="../soft/8727.html" target="_blank"><img src="../images/8727.gif">QuickTime</a></li>');
document.writeln('<li><a href="../soft/46636.html" target="_blank"><img src="../images/46636.gif">ABPlayer爱播</a></li>');
document.writeln('<li><a href="http://www.adtools.cn/click.csp?.a3=15672&url=http://www.skycn.com/soft/36276.html" target="_blank"><img src="../images/36276.gif">皮皮高清影视</a></li>');
document.writeln('<li><a href="http://www.skycn.com/soft/51839.html" target="_blank"><img src="../images/51839.gif">暴风转码</a></li>');