document.writeln('<li><a href="../soft/23.html" target="_blank"><img src="../images/23.gif">WinRAR</a></li>');
document.writeln('<li><a href="../soft/2345.html" target="_blank"><img src="../images/2345.gif">DAEMON Tools</a></li>');
document.writeln('<li><a href="../soft/27159.html" target="_blank"><img src="../images/27159.gif">搜狗拼音</a></li>');
document.writeln('<li><a href="../soft/35344.html" target="_blank"><img src="../images/35344.gif">谷歌拼音</a></li>');
document.writeln('<li><a href="../soft/39027.html" target="_blank"><img src="../images/39027.gif">腾讯QQ拼音</a></li>');
document.writeln('<li><a href="../soft/20835.html" target="_blank"><img src="../images/20835.gif">极点五笔</a></li>');
document.writeln('<li><a href="../soft/10654.html" target="_blank"><img src="../images/10654.gif">王码五笔</a></li>');
document.writeln('<li><a href="../soft/6905.html" target="_blank"><img src="../images/6905.gif">WPS Office</a></li>');
document.writeln('<li><a href="../soft/6854.html" target="_blank"><img src="../images/6854.gif">按键精灵</a></li>');
document.writeln('<li><a href="../soft/6216.html" target="_blank"><img src="../images/6216.gif">拼音加加</a></li>');
document.writeln('<li><a href="../soft/5741.html" target="_blank"><img src="../images/5741.gif">紫光拼音</a></li>');
document.writeln('<li><a href="../soft/4160.html" target="_blank"><img src="../images/4160.gif">智能陈桥五笔</a></li>');
document.writeln('<li><a href="../soft/4088.html" target="_blank"><img src="../images/4088.gif">万能五笔</a></li>');
document.writeln('<li><a href="../soft/3066.html" target="_blank"><img src="../images/3066.gif">极品五笔</a></li>');
document.writeln('<li><a href="../soft/3076.html" target="_blank"><img src="../images/3076.gif">Adobe Reader</a></li>');
document.writeln('<li><a href="../soft/1682.html" target="_blank"><img src="../images/1682.gif">虚拟光驱</a></li>');
document.writeln('<li><a href="../soft/32866.html" target="_blank"><img src="../images/32866.gif">PDF阅读精灵</a></li>');
document.writeln('<li><a href="../soft/44655.html" target="_blank"><img src="../images/44655.gif">谷歌金山词霸</a></li>');
document.writeln('<li><a href="../soft/42757.html" target="_blank"><img src="../images/42757.gif">有道桌面词典</a></li>');