package org.tingoo.gaapi.gz.bean;

// Generated 2011-1-14 9:02:39 by Hibernate Tools 3.2.4.GA

import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private int id;
	private Category category;
	private String code;
	private String name;
	private Clob description;
	private Set<Category> categories = new HashSet<Category>(0);

	public Category() {
	}

	public Category(int id) {
		this.id = id;
	}

	public Category(int id, Category category, String code, String name,
			Clob description, Set<Category> categories) {
		this.id = id;
		this.category = category;
		this.code = code;
		this.name = name;
		this.description = description;
		this.categories = categories;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Clob getDescription() {
		return this.description;
	}

	public void setDescription(Clob description) {
		this.description = description;
	}

	public Set<Category> getCategories() {
		return this.categories;
	}

	public void setCategories(Set<Category> categories) {
		this.categories = categories;
	}

}
