package org.tingoo.gaapi.gz.bean;

// Generated 2011-1-20 17:54:51 by Hibernate Tools 3.2.4.GA

/**
 * WageId generated by hbm2java
 */
public class WageId implements java.io.Serializable {

	private String code;
	private String yuefen;

	public WageId() {
	}

	public WageId(String code, String yuefen) {
		this.code = code;
		this.yuefen = yuefen;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getYuefen() {
		return this.yuefen;
	}

	public void setYuefen(String yuefen) {
		this.yuefen = yuefen;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WageId))
			return false;
		WageId castOther = (WageId) other;

		return ((this.getCode() == castOther.getCode()) || (this.getCode() != null
				&& castOther.getCode() != null && this.getCode().equals(
				castOther.getCode())))
				&& ((this.getYuefen() == castOther.getYuefen()) || (this
						.getYuefen() != null
						&& castOther.getYuefen() != null && this.getYuefen()
						.equals(castOther.getYuefen())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCode() == null ? 0 : this.getCode().hashCode());
		result = 37 * result
				+ (getYuefen() == null ? 0 : this.getYuefen().hashCode());
		return result;
	}

}
